import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/office_space_model.dart';
import '../services/supabase_service.dart';

class AddOfficeSpaceScreen extends StatefulWidget {
  const AddOfficeSpaceScreen({super.key});

  @override
  State<AddOfficeSpaceScreen> createState() => _AddOfficeSpaceScreenState();
}

class _AddOfficeSpaceScreenState extends State<AddOfficeSpaceScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _latitudeController = TextEditingController();
  final _longitudeController = TextEditingController();
  final _capacityController = TextEditingController();
  final _pricePerHourController = TextEditingController();

  final SupabaseService _supabaseService = SupabaseService();

  void _submitForm() async {
    if (_formKey.currentState!.validate()) {
      final client = Supabase.instance.client;
      final user = client.auth.currentUser;
      if (user == null) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('You must be logged in to add a space.')),
        );
        return;
      }

      final newSpace = OfficeSpace(
        id: '', // Will be generated by the database
        ownerId: user.id,
        title: _titleController.text,
        description: _descriptionController.text,
        location: {
          'coordinates': [double.parse(_longitudeController.text), double.parse(_latitudeController.text)],
          'address': '', // Would typically get from geocoding
          'city': '',
          'state': '',
          'zipCode': '',
          'country': '',
        },
        capacity: int.parse(_capacityController.text),
        pricing: {
          'hourly': double.parse(_pricePerHourController.text),
          'daily': double.parse(_pricePerHourController.text) * 8,
          'weekly': double.parse(_pricePerHourController.text) * 40,
          'monthly': double.parse(_pricePerHourController.text) * 160,
        },
        photos: [], // Placeholder for photo URLs
        amenities: [], // Placeholder for amenities
      );

      await _supabaseService.addOfficeSpace(newSpace);

      if (!mounted) return;
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add New Office Space'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(labelText: 'Title'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a title';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(labelText: 'Description'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a description';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _latitudeController,
                decoration: const InputDecoration(labelText: 'Latitude'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a latitude';
                  }
                  try {
                    double.parse(value);
                  } catch (e) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _longitudeController,
                decoration: const InputDecoration(labelText: 'Longitude'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a longitude';
                  }
                  try {
                    double.parse(value);
                  } catch (e) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _capacityController,
                decoration: const InputDecoration(labelText: 'Capacity'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter the capacity';
                  }
                  try {
                    int.parse(value);
                  } catch (e) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _pricePerHourController,
                decoration: const InputDecoration(labelText: 'Price per Hour'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a price';
                  }
                  try {
                    double.parse(value);
                  } catch (e) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _submitForm,
                child: const Text('Add Space'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
