import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/office_space_model.dart';
import '../services/firestore_service.dart';

class AddOfficeSpaceScreen extends StatefulWidget {
  const AddOfficeSpaceScreen({super.key});

  @override
  State<AddOfficeSpaceScreen> createState() => _AddOfficeSpaceScreenState();
}

class _AddOfficeSpaceScreenState extends State<AddOfficeSpaceScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _latitudeController = TextEditingController();
  final _longitudeController = TextEditingController();
  final _capacityController = TextEditingController();
  final _pricePerHourController = TextEditingController();

  final FirestoreService _firestoreService = FirestoreService();

  void _submitForm() async {
    if (_formKey.currentState!.validate()) {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('You must be logged in to add a space.')),
        );
        return;
      }

      final newSpace = OfficeSpace(
        id: '', // ID will be generated by Firestore
        ownerId: user.uid,
        title: _titleController.text,
        description: _descriptionController.text,
        location: GeoPoint(
          double.parse(_latitudeController.text),
          double.parse(_longitudeController.text),
        ),
        photos: [], // Placeholder for photo URLs
        amenities: [], // Placeholder for amenities
        capacity: int.parse(_capacityController.text),
        pricing: {
          'per_hour': double.parse(_pricePerHourController.text),
        },
      );

      await _firestoreService.addOfficeSpace(newSpace);

      if (!mounted) return;
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add New Office Space'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(labelText: 'Title'),
                validator: (value) => value!.isEmpty ? 'Please enter a title' : null,
              ),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(labelText: 'Description'),
                validator: (value) => value!.isEmpty ? 'Please enter a description' : null,
              ),
              TextFormField(
                controller: _latitudeController,
                decoration: const InputDecoration(labelText: 'Latitude'),
                keyboardType: TextInputType.number,
                validator: (value) => value!.isEmpty ? 'Please enter a latitude' : null,
              ),
              TextFormField(
                controller: _longitudeController,
                decoration: const InputDecoration(labelText: 'Longitude'),
                keyboardType: TextInputType.number,
                validator: (value) => value!.isEmpty ? 'Please enter a longitude' : null,
              ),
              TextFormField(
                controller: _capacityController,
                decoration: const InputDecoration(labelText: 'Capacity'),
                keyboardType: TextInputType.number,
                validator: (value) => value!.isEmpty ? 'Please enter the capacity' : null,
              ),
              TextFormField(
                controller: _pricePerHourController,
                decoration: const InputDecoration(labelText: 'Price per Hour'),
                keyboardType: TextInputType.number,
                validator: (value) => value!.isEmpty ? 'Please enter a price' : null,
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _submitForm,
                child: const Text('Add Space'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
